name: chatify_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16
  firebase_auth: ^3.3.18
  firebase_analytics: ^9.1.8
  cloud_firestore: ^3.1.15
  provider: ^6.0.2
  get_it: ^7.2.0
  file_picker: ^4.5.1
  flutter_spinkit: ^5.1.0
  timeago: ^3.2.2
  flutter_keyboard_visibility: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
